app_name: PiGallery

sidebar_items:
  subjects:
    address: '/subjects'
    icon: 'fas fa-fw fa-camera'
    text: 'Subjects'
  locations:
    address: '/locations'
    icon: 'fas fa-fw fa-mountain'
    text: 'Locations'
  time:
    address: '/months'
    icon: 'fas fa-fw fa-clock'
    text: 'Timeline'
  updates:
    address: '/imports'
    icon: 'fas fa-fw fa-gift'
    text: 'Updates'